name: Continous Integration and Deployment
on:
  push:
    branches:
      - main

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
      - name: build
        run: yarn build

Deploy:
  needs: Build
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'
  steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "22.x"
    - name: Install vercel CLI
      run: yarn global add vercel
    - name: Pull Vercel Environment Variables
      run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy to Vercel
      run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN }}
